name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file spring-petclinic-main/pom.xml

    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-cr6qrttds78s73c2sb4g 
        api-key: rnd_D7dWpTNUbzAIOKXoQmdNjWg8n5Dk
          
    - name: Deploy na EC2
      run: |
           echo "${{secrets.KEY_F}}" >private_key && chmod 400 private_key
           ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-35-172-80-252.compute-1.amazonaws.com "
                     cd POC/spring-petclinic-main &&
                     git pull &&
                     mvn clean package -DskipTests &&
                     ./executar.sh "
                                          
     
